server:
  error:
    whitelabel:
      enabled: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://litmus-db-cluster.cluster-c8342irl58my.us-east-1.rds.amazonaws.com:5432/litmusdb
    username: postgresAdmin
    password: iZ0DRotQWETrf0Eo1kEW
    driver-class-name: org.postgresql.Driver
